apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "course-app.fullname" . }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "course-app.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "course-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "course-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "course-app.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: {{ include "course-app.postgresHost" . | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "course-app.fullname" . }}-secret
                  key: FLASK_SECRET_KEY
            - name: APP_BANNER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "course-app.fullname" . }}-config
                  key: APP_BANNER
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "course-app.fullname" . }}-config
                  key: APP_VERSION
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
