apiVersion: v1
kind: Secret
metadata:
  name: {{ include "course-app.fullname" . }}-secret
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLASK_SECRET_KEY: {{ .Values.secret.flaskSecretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- if .Values.cnpg.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "course-app.cnpgCredentialsSecretName" . }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}
{{- end }}
