apiVersion: v1
kind: Secret
metadata:
  name: {{ include "course-app.fullname" . }}-secret
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLASK_SECRET_KEY: {{ .Values.secret.flaskSecretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
